- src/SolarEclipse2024.vue
- src/main.ts
This continues to strip out unneeded annular eclipse components and would close #8 when merged.
> UI updates

- src/LocationSelector.vue
- src/SolarEclipse2024.vue
This updates the colormap for the cloud data and adds a simple colorbar. I have also used a layer group instead of a list to take adavntage of leaflets built in methods for handling the data
> Updates to the cloud colormap

- public/index.html
Resolves #31 by updating the favicon domain.
Edit: Well, this story isn't deployed yet - but this will make sure the favicon works when it is.
> Fix deployed favicon

- src/SolarEclipse2024.vue
- Add 3rd dialog with teaser content
- Add "Hist." to mobile cloud cover chip
> UI updates 3

- src/LocationSelector.vue
This PR moves the red selected location dot, as well as the central eclipse path, above everything else on the Leaflet map (in particular, above the cloud layer).
What I did here for the selected circle would be easy to move back into the toolkit if we want. The eclipse path part is obviously not going back upstream anyway, so I just identified which GeoJSON is the center by looking at the URL.
> Put selected dot and central eclipse path above everything else

- src/SolarEclipse2024.vue
After putting a note in #43 about putting back the splash screen before merging, I forgot.
> Put back splash screen

- src/PlaybackControl.vue
- src/SolarEclipse2024.vue
fixes some missing code resulting in the playback control not working on small screens. 
also makes the "slowed for eclipse" notice more subtle
> fix playback control bugs

- src/PlaybackControl.vue
- src/SolarEclipse2024.vue
Making a bunch of small changes to resolve #75
> Small fixes

- package.json
- src/SolarEclipse2024.vue
This PR resolves #77 by updating the endpoint that we're using to submit data to be a newly-created endpoint specific to this story (the currently referenced endpoint doesn't actually exist). Additionally, since we aren't using preset locations here, I've removed that information from the request body.
> Update data submission endpoint

- src/LocationSelector.vue
- src/SolarEclipse2024.vue
- src/eclipse_predict.ts
This brings this dev branch up to date with main including the new database connections
> Bring up to date with main

- src/AdvancedWeatherView.vue
- src/BarChart.vue
- src/CloudDataExplainer.vue
- src/ColorBar.vue
- src/DefineTerm.vue
- src/LineChart.vue
- src/SolarEclipse2024.vue
- src/main.ts
Implementing the cloud data explorer view guideline and additional pages for learners.
> Implement-detailed-weather-scaffolding

- src/AdvancedWeatherView.vue
- src/SolarEclipse2024.vue
This PR updates this branch to send data indicating how much time the user has spent with the advanced weather view open.
> Keep track of how long advanced weather view is open

- src/SolarEclipse2024.vue
- src/shims-wwt.d.ts
- src/wwt-hacks.ts
This PR provides a partial fix for the strange issues that we've been seeing on Safari. This doesn't fix the real problem (which I still haven't quite pinned down), but it is an improvement.
> Partial fix for Safari issues

- src/SolarEclipse2024.vue
This PR updates the `box-sizing` on the splash screen to prevent the splash screen from scrolling.
> Prevent splash screen from scrolling

- src/LocationSearch.vue
- src/SolarEclipse2024.vue
- src/main.ts
This PR addresses the latest comments from recruited user testers assigned to Pat
> Last UI updates

- src/SolarEclipse2024.vue
- Update user guide to account for new text
- Remove extra space in splash list
- Update splash new/old text to not reference "school."
- Update margins so list content wouldn't be off center on small phone
> Tiny edits for updated splash text

- src/LocationSelector.vue
- src/SolarEclipse2024.vue
This PR attempts to fix an issue where the Leaflet credits div was displaying in the wrong position on iPhone browsers.
> Fix Leaflet credit div positioning on mobile WebKit

- src/LocationSelector.vue
This PR decreases the zoom level used when going to a location after a search from 10 down to 8.
> Adjust zoom level used when zooming from location search

- src/SolarEclipse2024.vue
Fix the eclipse chip size per #141
> fix eclipse chip size

- src/SolarEclipse2024.vue
Add a banner when the sun is below the horizon or rising/setting per #141
> add horizon banner

- src/EclipseTimer.vue
- src/OpenMeteoForecast.vue
- src/SolarEclipse2024.vue
- src/main.ts
This adds a weather forecast dialog. There are some styling issues (like the button size. we might want to stick with a font-awesome icon).
> Add weather forecast dialog

- .github/workflows/build-deploy.yml
- src/OpenMeteoForecast.vue
- src/SolarEclipse2024.vue
This PR updates the calls to OpenMeteo to use the customer endpoint with our API key.
> Use OpenMeteo API key

- src/EclipseTimer.vue
Updates to the eclipse timer so that it will show the time till totality (if in path of totality) or max eclipse, and the time left in partial eclipse, otherwise say the eclipse has passed
> Update eclipse timer

- public/index.html
- public/site.webmanifest
This PR builds on #159 by setting the shortcut titles as well.
> Update shortcut name
