cosmicds/solar-eclipse-2024

.github/workflows/build-deploy.yml
.github/workflows/build.yml

This PR adds our standard build and deployment workflows. We obviously don't have BrowserStack testing yet, but when we do we can just uncomment the relevant lines to add that in.

Add build and deployment workflows

---

.github/workflows/build-deploy.yml

This PR updates the deployment workflow to not deploy the story if it's marked as a draft.
With the way things are set up, it's not easy to test that the CI workflow runs correctly until we merge, so if there are any needed tweaks I can handle them after.

Check if draft before deploying

---

src/SolarEclipse2024.vue
src/wwt-hacks.ts

This PR aims to resolve #19. The root of the problem is that whether or not the Sun was entirely inside the Moon depended on the screen resolution - basically, a small sliver of the Sun not covered by the Moon would be lost at low zoom due to screen resolution. This, combined with the fact that we'd already changed the Sun-Moon distance calculation to use a more precise method meant that we were trying to solve a screen-space describing the intersection of the circles, when no such intersection existed.
The solution here is to essentially free ourselves of some of the resolution-based issues by using the fraction pixel values where the sun and moon centers "should" be. This should keep everything in agreement and allow us to "know" that the Sun isn't completely covered by the Moon, even …

Fix issue with annotation at certain zooms

---

src/SolarEclipse2024.vue

This PR solves #12. This was a tricky problem with a surprisingly simple solution.
Basically, the way that the `Place` tracking works is that, when we try to access the camera of a `Place` that's tracking an object, the getter looks up the location of that object and updates the camera appropriately. But until something actually calls that camera parameter getter, nothing actually gets updated. Since this doesn't happen until something changes in WWT, we were seeing the incorrect Moon sprite because the stored position is incorrect.
Once we know what's causing this, though, the solution is simple. We just explicitly tell the place to update the planet's location.

Use correct initial Moon sprite

---

src/LocationSelector.vue
src/SolarEclipse2024.vue

This PR keeps the sky opaque in Sun scope mode, while leaving the sky mode opacity transition unchanged.
Edit: Also updating this PR to only show cloud cover data on the appropriate tab. This part of the PR is a bit bolted on, but so is showing the cloud cover data in general, so I think that's unavoidable.

Keep sky opaque in Sun scope mode and only show cloud data on appropriate tab

---

src/LocationSelector.vue
src/SolarEclipse2024.vue

The map will automatically change the basemap if the url in the `map-options` prop is changed. If no new url is passed, it will switch to the default map.

allow the basemap url to switch

---

public/index.html

Having our domain name be projects.cosmicds.cfa.harvard.edu instead of cosmicds.github.io requires a new analytics tag. We will have to update the headers on all our resources.

The new domain name requires a new analytics tag

---

src/SolarEclipse2024.vue

This PR updates the tracking behavior when not centered on the Sun. Currently, we just keep the camera in place. This PR updates the behavior so that the "offset" of the current position from the Sun (offset here meaning the screen-space distance) is kept constant. The offset amount is updated each time we get a pointer up event on the canvas.

Sun offset tracking

---

src/SolarEclipse2024.vue

With Jon's #41 update to allow tracking off center, we needed to coordinate the switches and offer the user a way to center back on the Sun. It ended up being way more complicated than I thought it would be, and I'm not sure my changes are bulletproof, but everything seems to behave how I intended it to. It would be good if someone could please check and make sure everything makes sense. I had to delete/disable some things where I was not 100% sure what they were meant to do, and it's possible I left in things or added things that are not really necessary. This is what I intended:
- If user is tracking Sun (`toggleTrackSun = true`), we need to make sure that tracking is active whether we are centered on the Sun (`trackSun`) or not centered (`trackSunOffset`).
- If user is not tracking …

Lots of UI updates

---

src/CloudCover.vue

This PR fixes a bad prop type declaration in the `CloudCover` component, which can cause a warning in the browser console.

Fix prop type declaration in cloud cover component

---

src/GeolocationButton.vue
src/SolarEclipse2024.vue

Improves the handling of permissions per #42 for the Geolocation Button, but internally and provides an emit for handling that in the template. It no longer has an emit to "ask for permissions" as there is nothing the parent can do. Asking permission is initiated using `navigator.geolocation.getCurrentPosition`. This is currently setup to check for the permissions and broadcast that to the parent. It will hide the button if it permissions aren't already granted and won't try to ask

improve location button permissions handling

---

.github/workflows/build-deploy.yml
src/SolarEclipse2024.vue

This PR updates the selected location text to use MapBox. The previous lat/lon text is still used as a fallback in case we have some issue hitting the API.
Since the call to the MapBox API is necessarily asynchronous, I changed `selectedLocationText` to be part of the component data, and it's updated via an async method that gets called when the location is updated. The MapBox handling code looks kinda gnarly, but it's mostly just checking that the features that we expect to exist are actually there.

Use MapBox for determining location text

---

src/SolarEclipse2024.vue

This PR builds off of #52 with a couple more updates:
* The initial location text is now hardcoded to "Nazas, DUR". This fixes a production issue that we were seeing with only the first MapBox request failing, and additionally saves us one MapBox request per use of the app.
* Since this is a North America-focused story, country text has been removed for the US, Canada, and Mexico. State/province text has also been added for Canada and Mexico.

Updates to location text

---

src/SolarEclipse2024.vue

This PR resolves #58 by setting WWT to play when the user closes the intro dialog (the one after the splash screen). This is handled in the listener for `inIntro` (which is the `v-model` flag for the intro dialog).

Start playing WWT time when the intro dialog is closed

---

src/SolarEclipse2024.vue

This PR adds a query parameter for hiding the splash screen as requested in #67. Using a query of `splash=false` (`False` is also accepted) will hide the splash screen.
@patudom Do we want this to hide the intro dialog as well? Currently it does - my thought is that, unless one is working on the intro dialog, it would also be nicer to skip that during development.

Add query parameter for hiding splash screen

---

src/SolarEclipse2024.vue

This will resolve #27. 
For now, I've added the information in the general Data Story credits section, which is kind of buried under all the interface instructions.
We might want to consider making that last button 2 tabs, where 1 is the interface instructions & the other is all the data and team credits. I will create an issue for us to do that if we have time.

Add data credits to story

---

src/SolarEclipse2024.vue

This PR increases the size of the guided content on mobile to cover the entire screen. This is intended to address #85. I've also adjusted the sizing of the elements in the guided content to give the map as much space as is appropriate.

Make guided content fullscreen on mobile

---

src/SolarEclipse2024.vue

This PR fixes a bug where the info time is not recorded properly if the user leaves the page/switches tabs while the info window is still open.

Record info time if window is still visible

---

src/AdvancedWeatherView.vue
src/DefineTerm.vue
src/SolarEclipse2024.vue

This PR 
- temporarily changes the `v-text-field` label right after the location is changed so there is a clear indication when the text box is used. 
- fixes the AWV help icon so that it get's focus properly
- DefineTerm tooltip can now be displayed for a settable number of seconds when mounted (per request)
- The selectedTimezone needs to updated at mount so that it can be set by query parameters

change v-text-field label after change

---

src/AdvancedWeatherView.vue
src/DefineTerm.vue

Pushes the tooltip down in AWV for small displays so the button can be seen

push tool down on small screens

---

src/SolarEclipse2024.vue

This PR adds more items to the data that we keep track of. The new items are:
* How long the user guide has been open for
* How long the eclipse timer has been open
* Which locations the user went to from the text search (locations from text search now won't get added to either of the map location lists)

Add more data tracking

---

src/AdvancedWeatherView.vue
src/SolarEclipse2024.vue

This PR resolves #117:
* The first time a user switches to either of the cloud cover paths, the current location is added to the selected cloud cover locations list
* Keep track of the count of locations selected in the advanced weather view (but not the locations themselves, as they'll all end up in the cloud cover locations list)

Location tracking updates

---

public/index.html

I updated some of the meta data in our header to try to improve search results. Apparently, it can take weeks to months for these types of changes to make a difference, so who knows, but at least we should have a proper blurb returned with search results now, instead of this.
One thing I read was that our page title should include our organization name. Not sure how much that matters, so we can change that if others think that looks weird.

Add seo keywords

---

src/SolarEclipse2024.vue

This PR updates the MapBox request that we send to allow searching by postcode. This means that users can now search for their location in the story using their ZIP code.

Allow searching for a location by ZIP code

---

src/SolarEclipse2024.vue

As the title says, this PR updates the new mobile layout to omit the detailed cloud cover view tab (and, by extension, the advanced weather view, since that's only accessible from that tab).

Don't show advanced cloud cover/AWV on mobile

---

src/SolarEclipse2024.vue

This PR pauses the display whenever one of the overlays is opened (the guided content on narrow, the user guide, the info sheet, the eclipse timer, the advanced weather view and the weather info box). if it was already paused it does nothing, otherwise it keeps track of how many times it was triggered and then only unpauses once the final dialog is closed.

Pause when overlay is open

---

src/SolarEclipse2024.vue

This PR updates the app to keep track of how long the forecast info card is open for. The setup here follows the same pattern that we've used for most of the other time tracking.

Add tracking of forecast info time

---

src/SolarEclipse2024.vue

This PR fixes an issue with the forecast info timestamp not being reset. (This was supposed to be in #152 but I forgot to push my local commit).

Reset forecast info start timestamp

---

src/AdvancedWeatherView.vue
src/SolarEclipse2024.vue

I noticed that, currently, we make two MapBox requests every time we change our location. After looking into this, it turns out that the reason is that the AWV makes its own request to update its location name info. This PR attempts to cut down on the number of requests by only having the AWV make a request to update its location name when it's open (and then make a request when it's opened to get it back up-to-date). There may be a few more places that we can trim down on requests, but I think this should get rid of the lion's share of duplication.

Reduce number of MapBox requests

---

public/index.html
public/site.webmanifest

This PR adds some `link` tags to our index file that sets the icons when a user creates a shortcut to the page on iOS/Android. iOS uses the [`apple-touch-icon` links](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html), whereas Android uses the `icon` link and apparently [needs a site manifest](https://stackoverflow.com/questions/78016974/include-icon-when-add-to-home-screen-from-android-chrome)

Set icons for mobile browser shortcuts

---

src/SolarEclipse2024.vue

This PR adds a button that changes the app time to the system time, clamped to be within our min and max time values on the slider. Currently I've set the button to be disabled when the current time is outside of that range.
Since the system time isn't reactive, I've set a function to run on a 1-second interval that checks whether the system time is inside of the range. Also, while WWT has a function for resetting to the current system time, we would also need to update the app time, which triggers a WWT time update. Thus there's really no benefit - we can just update the app time and let the watcher update WWT.
Marking as a draft so that we can set up styling.

Add button to change app time to system time

---

src/CreditLogos.vue
src/GeolocationButton.vue

This PR updates the local credit logos component to use the NASA Grantee logo. It also updates the import for the Vuetify circular progress component.

Use NASA Grantee logo
